
################################################################################
#
#  Copyright (c) 2020, Perry L Miller IV
#  All rights reserved.
#  MIT License: https://opensource.org/licenses/mit-license.html
#
################################################################################

################################################################################
#
#  Travis configuration file.
#
#  Pipeline results are here:
#
#    https://travis-ci.com/github/perryiv/generic_scene_graph
#
#  Resources:
#
#    https://docs.conan.io/en/latest/integrations/ci/travisci.html
#    https://docs.travis-ci.com/user/deployment/bintray
#    https://docs.travis-ci.com/user/docker/
#    https://docs.travis-ci.com/user/job-lifecycle/
#    https://docs.travis-ci.com/user/languages/cpp/
#    https://docs.travis-ci.com/user/reference/windows/
#    https://stackoverflow.com/questions/61874708/how-can-i-build-visual-studio-2019-projects-on-travis-ci
#
################################################################################

language: cpp

branches:
  only:
    - master

jobs:
  include:

    - name: Linux_GCC_10_CPP_17
      os: linux
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/home/conan conanio/gcc10 /bin/bash -c "CPP_STANDARD=17 sh ./build.sh"

    - name: Linux_GCC_10_CPP_14
      os: linux
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/home/conan conanio/gcc10 /bin/bash -c "CPP_STANDARD=14 sh ./build.sh"

    - name: Linux_GCC_10_CPP_11
      os: linux
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/home/conan conanio/gcc10 /bin/bash -c "CPP_STANDARD=11 sh ./build.sh"

    - name: Linux_GCC_9_CPP_17
      os: linux
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/home/conan conanio/gcc9 /bin/bash -c "CPP_STANDARD=17 sh ./build.sh"

    - name: Linux_GCC_9_CPP_14
      os: linux
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/home/conan conanio/gcc9 /bin/bash -c "CPP_STANDARD=14 sh ./build.sh"

    - name: Linux_GCC_9_CPP_11
      os: linux
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/home/conan conanio/gcc9 /bin/bash -c "CPP_STANDARD=11 sh ./build.sh"

    - name: Linux_GCC_8_CPP_17
      os: linux
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/home/conan conanio/gcc8 /bin/bash -c "CPP_STANDARD=17 sh ./build.sh"

    - name: Linux_GCC_8_CPP_14
      os: linux
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/home/conan conanio/gcc8 /bin/bash -c "CPP_STANDARD=14 sh ./build.sh"

    - name: Linux_GCC_8_CPP_11
      os: linux
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/home/conan conanio/gcc8 /bin/bash -c "CPP_STANDARD=11 sh ./build.sh"

    - name: Apple_Clang_9_CPP_17
      os: osx
      install:
        - brew install ninja
      script:
        - CPP_STANDARD=17 sh ./build.sh

    - name: Apple_Clang_9_CPP_14
      os: osx
      install:
        - brew install ninja
      script:
        - CPP_STANDARD=14 sh ./build.sh

    - name: Apple_Clang_9_CPP_11
      os: osx
      install:
        - brew install ninja
      script:
        - CPP_STANDARD=11 sh ./build.sh

    - name: Visual_Studio_2019_CPP_17
      os: windows
      env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - choco install ninja
      script:
        - CPP_STANDARD=17 sh ./build.sh

    - name: Visual_Studio_2019_CPP_14
      os: windows
      env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - choco install ninja
      script:
        - CPP_STANDARD=14 sh ./build.sh

    - name: Visual_Studio_2019_CPP_11
      os: windows
      env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - choco install ninja
      script:
        - CPP_STANDARD=11 sh ./build.sh
