################################################################################
#
#  Travis configuration file.
#
#  Pipeline results are here:
#
#    https://travis-ci.com/github/perryiv/generic_scene_graph
#
#  Resources:
#
#    https://docs.conan.io/en/latest/integrations/ci/travisci.html
#    https://docs.travis-ci.com/user/deployment/bintray/
#
################################################################################

language: cpp

branches:
  only:
    - master

before_install:
  - eval "${MATRIX_EVAL}"

jobs:
  include:
    - name: Ubuntu Focal
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10.2
      env:
        - MATRIX_EVAL="CC=gcc-10.2 && CXX=g++-10.2"
    - name: Ubuntu Bionic
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9.2
      env:
        - MATRIX_EVAL="CC=gcc-9.2 && CXX=g++-9.2"
    - name: Ubuntu Xenial
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8.4
      env:
        - MATRIX_EVAL="CC=gcc-8.4 && CXX=g++-8.4"
    - name: Apple
      os: osx
    - name: Windows
      os: windows
      env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

script:
  - cmake --version
  - git --version
  - gcc --version
  - clang --version
  - echo $CC
  - echo $CXX
