
################################################################################
#
#  Copyright (c) 2020, Perry L Miller IV
#  All rights reserved.
#  MIT License: https://opensource.org/licenses/mit-license.html
#
################################################################################

################################################################################
#
#  Travis configuration file.
#
#  Pipeline results are here:
#
#    https://travis-ci.com/github/perryiv/generic_scene_graph
#
#  Resources:
#
#    https://docs.conan.io/en/latest/integrations/ci/travisci.html
#    https://docs.travis-ci.com/user/deployment/bintray/
#
################################################################################

language: cpp

branches:
  only:
    - master

jobs:
  include:

    - name: Ubuntu Focal
      dist: focal
      services:
        - docker
      script:
        - docker run --rm conanio/gcc10 /bin/bash -c "gcc --version && cmake --version"

    # - name: Apple
    #   os: osx
    #
    # - name: Windows
    #   os: windows
    #   env:
    #     - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
    #   install:
    #     - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

# script:
#   - cmake --version
#   - git --version
#   - gcc --version
#   - clang --version
#   - echo $CC
#   - echo $CXX
