
################################################################################
#
#  Copyright (c) 2020, Perry L Miller IV
#  All rights reserved.
#  MIT License: https://opensource.org/licenses/mit-license.html
#
################################################################################

################################################################################
#
#  Azure Pipelines configuration file.
#
#  Pipeline results are here:
#
#    https://dev.azure.com/perryiv/generic_scene_graph
#
#  Resources:
#
#    https://docs.conan.io/en/1.10/howtos/run_conan_in_docker.html
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases#timeouts
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables#secret-variables
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
#    https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container
#    https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio
#    https://github.com/actions/virtual-environments
#    https://github.com/conan-io/conan-docker-tools/blob/master/azure-pipelines.yml
#    https://github.com/jonico/libzengithub/blob/master/azure-pipelines.yml
#    https://github.com/microsoft/azure-pipelines-agent/issues/2043
#    https://github.com/microsoft/containerregistry
#    https://hub.docker.com/_/microsoft-windows-servercore
#    https://hub.docker.com/r/conanio/gcc8
#    https://jaylee.org/archive/2019/03/21/azure-devops-wasm-build-container.html
#    https://medium.com/@brentrobinson5/containerised-ci-cd-pipelines-with-azure-devops-74064c679f20
#
################################################################################

trigger:
- master

jobs:

- job: Linux_GCC_10_CPP_17
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: docker run --rm -v `pwd`:/home/conan conanio/gcc10 /bin/bash -c "CPP_STANDARD=17 sh ./build.sh"

- job: Linux_GCC_10_CPP_14
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: docker run --rm -v `pwd`:/home/conan conanio/gcc10 /bin/bash -c "CPP_STANDARD=14 sh ./build.sh"

- job: Linux_GCC_9_CPP_17
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: docker run --rm -v `pwd`:/home/conan conanio/gcc9 /bin/bash -c "CPP_STANDARD=17 sh ./build.sh"

- job: Linux_GCC_9_CPP_14
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: docker run --rm -v `pwd`:/home/conan conanio/gcc9 /bin/bash -c "CPP_STANDARD=14 sh ./build.sh"

- job: Linux_GCC_8_CPP_17
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: docker run --rm -v `pwd`:/home/conan conanio/gcc8 /bin/bash -c "CPP_STANDARD=17 sh ./build.sh"

- job: Linux_GCC_8_CPP_14
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: docker run --rm -v `pwd`:/home/conan conanio/gcc8 /bin/bash -c "CPP_STANDARD=14 sh ./build.sh"

# All versions of macOS appear to be using clang 11, so just doing that.

- job: Apple_Clang_11_CPP_17
  pool:
    vmImage: 'macOS-10.15'
  steps:
    - script: CPP_STANDARD=17 sh ./build.sh

- job: Apple_Clang_11_CPP_14
  pool:
    vmImage: 'macOS-10.15'
  steps:
    - script: CPP_STANDARD=14 sh ./build.sh

# On windows just using the host machine.

- job: Visual_Studio_2019_CPP_17
  pool:
    vmImage: 'windows-2019'
  steps:
    - script: CPP_STANDARD=17 sh ./build.sh

- job: Visual_Studio_2019_CPP_14
  pool:
    vmImage: 'windows-2019'
  steps:
    - script: CPP_STANDARD=14 sh ./build.sh
