
################################################################################
#
#  Copyright (c) 2020, Perry L Miller IV
#  All rights reserved.
#  MIT License: https://opensource.org/licenses/mit-license.html
#
################################################################################

################################################################################
#
#  Azure Pipelines configuration file.
#
#  Pipeline results are here:
#
#    https://dev.azure.com/perryiv/generic_scene_graph
#
#  Resources:
#
#    https://docs.conan.io/en/1.10/howtos/run_conan_in_docker.html
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases#timeouts
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables#secret-variables
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
#    https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container
#    https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio
#    https://github.com/actions/virtual-environments
#    https://github.com/conan-io/conan-docker-tools/blob/master/azure-pipelines.yml
#    https://github.com/jonico/libzengithub/blob/master/azure-pipelines.yml
#    https://github.com/microsoft/azure-pipelines-agent/issues/2043
#    https://github.com/microsoft/containerregistry
#    https://hub.docker.com/_/microsoft-windows-servercore
#    https://hub.docker.com/r/conanio/gcc8
#    https://jaylee.org/archive/2019/03/21/azure-devops-wasm-build-container.html
#    https://medium.com/@brentrobinson5/containerised-ci-cd-pipelines-with-azure-devops-74064c679f20
#
################################################################################

trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 0

  strategy:
    matrix:

      Linux_GCC_10_CPP_17:
        image_name: 'ubuntu-latest'
        build_generator: Ninja
        build_command: ninja
        cpp_standard: 17
        verbose_makefile: ON
        command: docker run --rm -v `pwd`:/home/conan conanio/gcc10 /bin/bash -c "sh ./scripts/before.sh && node ./scripts/ci.js"

      Linux_GCC_10_CPP_14:
        image_name: 'ubuntu-latest'
        build_generator: Ninja
        build_command: ninja
        cpp_standard: 14
        verbose_makefile: ON
        command: docker run --rm -v `pwd`:/home/conan conanio/gcc10 /bin/bash -c "sh ./scripts/before.sh && node ./scripts/ci.js"

      Linux_GCC_9_CPP_17:
        image_name: 'ubuntu-latest'
        build_generator: Ninja
        build_command: ninja
        cpp_standard: 17
        verbose_makefile: ON
        command: docker run --rm -v `pwd`:/home/conan conanio/gcc9 /bin/bash -c "sh ./scripts/before.sh && node ./scripts/ci.js"

      Linux_GCC_9_CPP_14:
        image_name: 'ubuntu-latest'
        build_generator: Ninja
        build_command: ninja
        cpp_standard: 14
        verbose_makefile: ON
        command: docker run --rm -v `pwd`:/home/conan conanio/gcc9 /bin/bash -c "sh ./scripts/before.sh && node ./scripts/ci.js"

      Linux_GCC_8_CPP_17:
        image_name: 'ubuntu-latest'
        build_generator: Ninja
        build_command: ninja
        cpp_standard: 17
        verbose_makefile: ON
        command: docker run --rm -v `pwd`:/home/conan conanio/gcc8 /bin/bash -c "sh ./scripts/before.sh && node ./scripts/ci.js"

      Linux_GCC_8_CPP_14:
        image_name: 'ubuntu-latest'
        build_generator: Ninja
        build_command: ninja
        cpp_standard: 14
        verbose_makefile: ON
        command: docker run --rm -v `pwd`:/home/conan conanio/gcc8 /bin/bash -c "sh ./scripts/before.sh && node ./scripts/ci.js"

      # All versions of macOS appear to be using clang 11, so just doing that.

      Apple_Clang_11_CPP_17:
        image_name: 'macOS-10.15'
        build_generator: 'Unix Makefiles'
        build_command: make
        cpp_standard: 17
        verbose_makefile: ON
        command: node ./scripts/ci.js

      Apple_Clang_11_CPP_14:
        image_name: 'macOS-10.15'
        build_generator: 'Unix Makefiles'
        build_command: make
        cpp_standard: 14
        verbose_makefile: ON
        command: node ./scripts/ci.js

      # On windows just using the host machine.

      Visual_Studio_2019_CPP_17:
        image_name: 'windows-2019'
        build_generator: 'Visual Studio'
        build_command: devenv
        cpp_standard: 17
        verbose_makefile: OFF
        extra_configure_arguments: '-Ax64'
        command: node ./scripts/ci.js

      Visual_Studio_2019_CPP_14:
        image_name: 'windows-2019'
        build_generator: 'Visual Studio'
        build_command: devenv
        cpp_standard: 14
        verbose_makefile: OFF
        extra_configure_arguments: '-Ax64'
        command: node ./scripts/ci.js

  pool:
    vmImage: $(image_name)

  variables:
    THIS_JOB_BUILD_GENERATOR: $(build_generator)
    THIS_JOB_BUILD_COMMAND: $(build_command)
    THIS_JOB_CPP_STANDARD: $(cpp_standard)
    THIS_JOB_VERBOSE_MAKEFILE: $(verbose_makefile)
    THIS_JOB_EXTRA_CONFIGURE_ARGUMENTS: $(extra_configure_arguments)

  steps:
    - script: $(command)
      displayName: Build
